module.exports = {
  root: true,
  env: {
    browser: true,
    es2021: true,
    jest: true,
  },
  parserOptions: {
    parser: "@typescript-eslint/parser",
    ecmaVersion: 2021,
    sourceType: "module",
  },
  extends: [
    "plugin:vue/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "plugin:import/typescript",
  ],
  plugins: ["simple-import-sort", "import"],
  rules: {
    "prettier/prettier": [
      "error",
      {
        arrowParens: "avoid",
        endOfLine: "auto",
        printWidth: 120,
        semi: false,
        singleQuote: true,
        tabWidth: 2,
        trailingComma: "all",
        overrides: [
          {
            files: ["*.yml", "*.yaml"],
            options: {
              singleQuote: false,
            },
          },
        ],
      },
    ],
    "vue/attributes-order": "off",
    "vue/component-name-in-template-casing": ["error", "kebab-case", {
      registeredComponentsOnly: true,
      ignores: [],
    }],
    "vue/html-indent": ["error", 2],
    "vue/max-attributes-per-line": "off",
    "vue/multi-word-component-names": "off",
    "vue/no-v-html": "off",
    "vue/html-self-closing": ["error", {
      html: {
        void: "always",
      },
    }],
    "vue/multiline-html-element-content-newline": "off",
    "vue/singleline-html-element-content-newline": "off",
    "class-methods-use-this": "off",
    "consistent-return": "off",
    "global-require": "off",
    "import/no-extraneous-dependencies": "off",
    "import/no-unresolved": "off",
    "no-console": process.env.ENVIRONMENT === "production" ? "error" : "off",
    "no-debugger": process.env.ENVIRONMENT === "production" ? "error" : "off",
    "no-new": "off",
    "no-param-reassign": "off",
    "no-plusplus": "off",
    "no-undef": "off",
    "no-underscore-dangle": "off",
    "no-unused-vars": "warn",
    "no-useless-constructor": "warn",
    "@typescript-eslint/no-explicit-any": "warn",
    "prefer-rest-params": "off",
    "padding-line-between-statements": ["error", {
      blankLine: "always",
      prev: "*",
      next: "return",
    }],
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
    "@typescript-eslint/no-unused-vars": "warn",
  },
};
